TEST

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,15 +1,27 @@
 name: Create and Merge Pull Request from DEV to MAIN
 
 on:
-  workflow_dispatch: # Evento manual para activar el workflow
+  workflow_dispatch:
 
 jobs:
   create-and-merge-pr:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
     - name: Checkout the repository
       uses: actions/checkout@v3
+
+    - name: Configure Git
+      run: |
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "actions@github.com"
+
+    - name: Verify dev branch exists
+      run: |
+        if ! git show-ref --verify --quiet refs/heads/dev; then
+          echo "Error: The branch 'dev' does not exist. Please create it first.";
+          exit 1;
+        fi
 
     - name: Create Pull Request
       id: create_pr
@@ -21,12 +33,12 @@ jobs:
         title: "PR automática de DEV a MAIN"
         body: |
           Este Pull Request fue generado automáticamente para pasar los cambios de `dev` a `main`.
-        labels: 'automerge-dev-to-main' # Etiqueta específica para auto-merge
+        labels: 'automerge-dev-to-main'
 
-    - name: Enable Auto-Merge for Specific PRs
+    - name: Enable Auto-Merge
       if: steps.create_pr.outputs.pull-request-url != '' # Solo si el PR se creó correctamente
       uses: pascalgn/automerge-action@v0.15.6
       env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
       with:
-        merge_label: 'automerge-dev-to-main' # Solo fusionar PRs con esta etiqueta
+        merge_label: 'automerge-dev-to-main'
